### ISSUE TITLE
Show incoming deploys in the dashboard

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#20]
Since `nanobox deploy` hits the api to register a deploy, it seems like we could show in the dashboard that a deploy has been initialized

**Comment by jedgalbraith** [comment]
When `nanobox deploy` initially hits the Odin API its only doing a GET for info about the current deploy. It doesn't actually register anything about the new deploy until it's ready for it to be deployed, which is when the dashboard starts to show the progress viewer. Also, even if we did display something about a deploy in progress, maybe after the initial GET, if anything failed during the local compile/deploy, we would need to clear that message since it would no longer be applicable.

So I'll close this issue for now, but let me know if it's important enough that we should consider rearchitecting.
