### ISSUE TITLE
Implement cancel on 3001 error

### ISSUE THREAD

**Issue by glinton** [nanobox-io/nanobox-dashboard-issues#30]
When a 3001 error is hit in the dashboard, it says:
![image](https://user-images.githubusercontent.com/2653109/27654476-84bfbc92-5bff-11e7-9ed0-13ca235a4714.png)

But the user can't cancel:
![image](https://user-images.githubusercontent.com/2653109/27654471-7edc20ea-5bff-11e7-972a-a92d5f2fcbf3.png)

**Comment by jedgalbraith** [comment]
Most 3001 errors have the "Cancel" option. This one didn't because it was past the point it could be cancelled. I've modified the messaging when canceling is not an option and replaced it with a messaging instructing the user to contact support. Although, this should be very rare. Several safe guards are in place to avoid getting into this situation. Some of them may not have been in place when this error occurred.
